### ISSUE TITLE
Regarding more runtime in LGE algorithm

### ISSUE THREAD

**Issue by natrajbhargav** [rachelselinar/ReGDS-Logic-Gate-Extraction#5] opened 2024-08-12 09:51 UTC
Dear  Rachel, i am waiting for your reply Please give me some solutions on how to resolve this issue.

**Comment by rachelselinar** [comment] 2024-08-19 15:36
Closing as duplicate of Issue #4

**Closed as completed by rachelselinar** 2024-08-19 15:36 UTC
